name: Run application

description: Run marketplace backend in background and wait for it to be ready

inputs:
  token:
    description: 'A Github PAT'
    required: true

runs:
  using: "composite"
  steps:
    - name: Start the backend
      shell: bash
      run: cargo run -p marketplace-core | tee marketplace-core.log &
      env:
        GITHUB_ID: githubid
        GITHUB_SECRET: githubsecret
        GITHUB_TOKEN: ${{ inputs.token }}
        DATABASE_URL: postgres://postgres:postgres@localhost/marketplace_db
        PRIVATE_KEY: "0x0"
        ACCOUNT_ADDRESS: "0x013b45368dff5bc78d01273d889c259ddd6b93a5269ed29a7475e04412dc46d0"
        PROFILE_ADDRESS: "0x069626c8be42f8599f028645561995ec69c3db3123643ccfc0d888a689a45b5c"
        REGISTRY_ADDRESS: "0x045d4cd01d5311b6c9a85619efb9a401857928dcdf72c79d4b6bf0052b922374"
        CONTRIBUTIONS_ADDRESS: "0x000b061238977bb1bd59c2c81bc5670fc2dfbac3854b7a25d9010dffb823b87f"
        JSON_RPC_URI: http://13.38.227.15:9545/
        NETWORK: alpha-goerli
        APIBARA_NODE_URL: http://localhost:7171
        API_KEY: ROOT
        API_URL: http://localhost:8000
        RUST_LOG: info
        STARKNET_ACCOUNT: "0x0"
        STARKNET_PRIVATE_KEY: "0x0"
        STARKNET_BADGE_REGISTRY_ADDRESS: "0x0689c0f3483daffd4e79a61f22f5a093f8adee50926a96161c23b058de70200d"
        STARKNET_CHAIN: TESTNET

    - name: Wait for the backend to be ready
      uses: ifaxity/wait-on-action@v1
      with:
        resource: http://localhost:8000/openapi.json
