name: Run Rust backend

description: Install and run Rust backend

runs:
  using: "composite"
  steps:
    - name: Copy the .env file
      shell: bash
      run: cp .env.example .env

    - name: Build the api
      shell: bash
      run: cargo build

    - name: Build the event-store
      shell: bash
      run: cargo build -p event-store

    - name: Build the event-listeners
      shell: bash
      run: cargo build -p event-listeners

    - name: Run the api
      shell: bash
      run: cargo run &> api.out.log &

    - name: Run the event listeners
      shell: bash
      run: cargo run -p event-listeners &> event-listeners.out.log &

    - name: Run the event store
      shell: bash
      run: cargo run -p event-store &> event-store.out.log &
