version: '3.8'
services:
  db:
    container_name: marketplace-db
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=marketplace_db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5060:80"
  starknet-devnet:
    container_name: starknet-devnet
    image: shardlabs/starknet-devnet:${BASE_TAG}
    command: --seed 0 --load-path /tmp/dump.pkl
    ports:
      - "5050:5050"
    volumes:
      - .:/tmp
  apibara:
    container_name: apibara
    image: apibara/starknet:ffbe469b2dadee8f5e3c11d35ee8b0f81915c63a
    command: /usr/local/bin/apibara-starknet start --custom-network name=devnet,url=http://starknet-devnet:5050 --poll-interval 500
    environment:
      RUST_LOG: info
    restart: always
    ports:
      - "7171:7171"
volumes:
  db:
    driver: local
