version: '3.8'
services:
  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=deathnote_contributions_db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5060:80"
  # starknet-devnet:
  #   image: shardlabs/starknet-devnet:${BASE_TAG}
  #   command: --seed 0 --load-path /tmp/dump.pkl
  #   ports:
  #     - "5050:5050"
  #   volumes:
  #     - .:/tmp
volumes:
  db:
    driver: local
