[package]
authors = ["OnlyDust <tech@onlydust.xyz>"]
default-run = "api"
description = "Backend services to operate the contribution marketplace."
edition = "2021"
homepage = "https://onlydust.xyz"
license-file = "LICENSE"
name = "api"
readme = "README.md"
repository = "https://github.com/onlydustxyz/marketplace-backend"
version = "1.0.0"

[dependencies]

# Async
async-trait = "0.1.56"
futures = {version = "0.3.21", features = ["alloc"]}
tokio = {version = "1.18.2", features = ["full"]}

# Database
diesel = {version = "1.4.8", default-features = false, features = [
  "postgres",
  "serde_json",
  "uuidv07",
  "chrono",
]}
uuid = {version = "0.8.2", default_features = false, features = [
  "v4",
  "serde",
]}

# Http client
reqwest = {version = "0.11", default-features = false}
url = "2.2.2"

# Http Server
juniper = {version = "0.15.10"}
juniper_rocket = {version = "0.8.2"}
rocket = {version = "0.5.0-rc.2", features = ["json", "uuid"]}

# AWS
rusoto_core = "0.48.0"
rusoto_s3 = "0.48.0"

# Logs
log = "0.4.17"

# Tracing
tracing = "0.1"

# Errors
anyhow = "1.0.57"
thiserror = "1.0.31"

# Serde
serde = {version = "1.0.137", features = ["derive"]}
serde_json = {version = "1.0.81"}

# Datetime
chrono = "0.4"

# Utils
derive_more = "0.99.17"
dotenv = "0.15.0"
rusty-money = {version = "0.4.1", features = ["iso", "crypto"]}
derive-getters = "0.2.0"
derive_setters = "0.1.5"
email_address = "0.2.4"
iban_validate = {version = "4.0.1", features = ["serde"]}
rust_decimal = "1.26.1"
infer = "0.12.0"
tokio-retry = "0.3"

# Github
octocrab = { git = "https://github.com/onlydustxyz/octocrab.git" }

# Local dependecies
domain = {path = "../common/domain", features = ["rocket"]}
event-store = {path = "../event-store"}
infrastructure = {path = "../common/infrastructure"}
derive = {path = "../common/derive"}
presentation = {path = "../common/presentation"}
olog = {path = "../common/olog"}

[dev-dependencies]
async-std = {version = "1.12.0", features = ["attributes"]}
lazy_static = "1.4.0"
rstest = "0.15.0"
mockall = "0.11.2"
mockall_double = "0.3.0"
assert_matches = "1.5"
