[workspace]

members = [
  "backend/api",
  "backend/common/domain",
  "backend/event-listeners",
  "backend/event-store",
  "backend/github-proxy",
  "backend/common/infrastructure",
  "backend/common/macros",
  "backend/common/presentation",
  "backend/common/testing",
  "backend/common/olog",
]
