[workspace]

members = [
  "marketplace-core",
  "marketplace-domain",
  "marketplace-event-store",
  "marketplace-indexer",
  "marketplace-infrastructure",
  "marketplace-tests",
  "marketplace-wrappers",
]
