[workspace]

members = [
  "backend/api",
  "backend/domain",
  "backend/event-listeners",
  "backend/event-store",
  "backend/github-proxy",
  "backend/infrastructure",
  "backend/macros",
  "backend/presentation",
  "backend/testing",
  "backend/olog",
]
