coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
          informational: true

ignore:
  - "marketplace-infrastructure/src/database/schema.rs"
  - "marketplace-wrappers"
