coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
          target: auto  # Auto adjust target based on previous commits
          threshold: 1% # Allow 1% drop off

ignore:
  - "marketplace-infrastructure/src/database/schema.rs"
  - "marketplace-wrappers"
