version: "3.8"
services:
  db:
    container_name: marketplace-db
    image: postgres:14.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace_db
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  httpmock:
    container_name: httpmock
    image: alexliesenfeld/httpmock:latest
    ports:
      - 5001:5000
    volumes:
      - ./docker/httpmocks:/mocks
    environment:
      HTTPMOCK_MOCK_FILES_DIR: /mocks

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672

  graphql-engine:
    image: hasura/graphql-engine:v2.15.0
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@db/marketplace_db
      DATABASE_URL: postgres://postgres:postgres@db/marketplace_db
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # use Hasura CLI to access the console, see projet README
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public

  hasura-auth:
    image: nhost/hasura-auth:latest
    depends_on:
      - db
      - graphql-engine
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@db/marketplace_db
      HASURA_GRAPHQL_GRAPHQL_URL: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"5152fa850c02dc222631cca898ed1485821a70912a6e3649c49076912daa3b62182ba013315915d64f40cddfbb8b58eb5bd11ba225336a6af45bbae07ca873f3","issuer":"hasura-auth"}'
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      AUTH_JWT_CUSTOM_CLAIMS: '{"projects_leaded":"projects_leaded[].project_id"}'
      AUTH_LOG_LEVEL: info

    ports:
      - "4000:4000"

volumes:
  httpmocks:
  db:
    driver: local
