version: "3.8"
services:
  frontend:
    labels:
      type: frontend
    container_name: frontend
    image: node:18-bullseye
    volumes:
      - .:/app
    command: bash -c "cd /app && yarn install && yarn dev --host"
    ports:
      - 5173:5173
    healthcheck:
      test: curl -f http://localhost:5173 || exit 1
      interval: 6s
      timeout: 1s
      retries: 50
    environment:
      VITE_HASURA_AUTH_BASE_URL: http://localhost:4000
      VITE_API_BASE_URL: http://localhost:8000/api
      VITE_HASURA_BASE_URL: http://localhost:8080
      VITE_HASURA_BASE_WS_URL: ws://localhost:8080
      VITE_LOGIN_URL: http://localhost:4000/signin/provider/github
      VITE_ENV: local
      VITE_MAINTENANCE:
      VITE_GTM_ID:
      VITE_LANGUAGES_FILTER: "CSS,Dockerfile,Handlebars,HCL,HTML,Jupyter Notebook,Makefile,Nix,Procfile,SCSS,Shell"
      VITE_ENABLE_DATADOG_LOG: false
      VITE_ENABLE_DATADOG_RUM: false
      VITE_CLOUDFLARE_RESIZE_W_100_PREFIX: https://onlydust.xyz/cdn-cgi/image/width=100/
      VITE_GENERIC_METADATA_URL: https://develop-app-metadata.onlydust.xyz/api/generic
