default:
  http:
    api_keys:
      graphql: $GITHUB_PROXY_GRAPHQL_API_KEY
  github:
    base_url: $GITHUB_BASE_URL
    personal_access_tokens: $GITHUB_PAT
    max_calls_per_request: $GITHUB_MAX_CALLS_PER_REQUEST

local:
  tracer:
    json: false
    ansi: true
    location: true

production:
  tracer:
    json: true
    ansi: false
    location: true
