default:
  http:
    api_keys:
      graphql: $GITHUB_PROXY_GRAPHQL_API_KEY
      github: $GITHUB_PROXY_GITHUB_API_KEY
  github:
    base_url: $GITHUB_BASE_URL
    personal_access_tokens: $GITHUB_PAT
    headers:
      api-key: $GITHUB_PROXY_GITHUB_API_KEY
      Fastly-Debug: "1"

local:
  tracer:
    json: false
    ansi: true
    location: true

production:
  tracer:
    json: true
    ansi: false
    location: true
