default:
  http:
    api_key: $GITHUB_PROXY_GRAPHQL_API_KEY
  github:
    base_url: $GITHUB_BASE_URL
    personal_access_token: $GITHUB_PAT

local:
  tracer:
    ansi: true

production:
  tracer:
    ansi: false
