[package]
name = "github-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
# Config
figment = {version ="0.10.8", features = ["env", "toml"]}

# Github
octocrab = "0.17.0"

# Http Server
juniper = {version = "0.15.10"}
juniper_rocket = {version = "0.8.2"}
rocket = {version = "0.5.0-rc.2", features = ["json", "uuid"]}

# Errors
anyhow = "1.0.57"

# Serde
serde = {version = "1.0.137", features = ["derive"]}

# Utils
derive_more = "0.99.17"
dotenv = "0.15.0"

# Local dependecies
infrastructure = {path = "../common/infrastructure"}
presentation = {path = "../common/presentation"}

[dev-dependencies]
