name: Code coverage

description: Launch application and run all tests while measuring code coverage

inputs:
  token:
    description: 'A Github PAT'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup cargo
      uses: ./.github/actions/cargo-setup

    - name: Setup environment
      uses: ./.github/actions/env-setup

    - name: Compile application
      uses: ./.github/actions/compile-application

    - name: Launch the backend
      uses: ./.github/actions/run-backend
      with:
        token: ${{ inputs.token }}

    - name: Launch the indexer
      uses: ./.github/actions/run-indexer
      with:
        token: ${{ inputs.token }}
        indexer_name: starknet

    - name: Setup cargo
      uses: ./.github/actions/cargo-setup
      with:
        key: coverage

    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.20.1'
        args: '--skip-clean --all-features -- --test-threads 1'
      env:
        API_KEY: ROOT
        GITHUB_TOKEN: ${{ inputs.token }}
        DATABASE_URL: postgres://postgres:postgres@localhost/marketplace_db

    - name: Upload results to codecov.io
      uses: codecov/codecov-action@v3
      with:
        files: cobertura.xml

    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml
