name: Code coverage

description: Launch application and run all tests while measuring code coverage

inputs:
  token:
    description: 'A Github PAT'
    required: true

  codecov_flag:
    description: 'Flag to upload code coverage results to codecov.io'
    required: true

  test_flags:
    description: 'Additional test flags to pass to cargo tarpaulin test command'
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup cargo
      uses: ./.github/actions/cargo-setup
      with:
        key: coverage

    - name: Setup environment
      uses: ./.github/actions/env-setup

    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.20.1'
        args: |
          --skip-clean
          --workspace
          --exclude marketplace-wrappers
          --exclude-files marketplace-infrastructure/src/database/schema.rs
          ${{ inputs.test_flags }}
      env:
        API_KEY: ROOT
        GITHUB_TOKEN: ${{ inputs.token }}
        DATABASE_URL: postgres://postgres:postgres@localhost/marketplace_db
        GITHUB_ID: githubid
        GITHUB_SECRET: githubsecret
        CONTRIBUTIONS_ADDRESS: "0x03f0e236a4cb1b20278ad5a7e790b29c6e5bac25c34fc3fb0c092f8e5275b512"
        NETWORK: alpha-goerli
        APIBARA_NODE_URL: http://localhost:7171
        API_URL: http://localhost:8000
        RUST_LOG: info

    - name: Upload results to codecov.io
      uses: codecov/codecov-action@v3
      with:
        files: cobertura.xml
        flags: ${{ inputs.codecov_flag }}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report-${{ inputs.codecov_flag }}
        path: cobertura.xml
