name: Code coverage

description: Launch application and run all tests while measuring code coverage

runs:
  using: "composite"
  steps:
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: "0.20.1"
        args: |
          --workspace
          ${{ inputs.test_flags }}
