name: Code coverage

description: Launch application and run all tests while measuring code coverage

inputs:
  test_flags:
    description: "Flags to pass to the cargo tarpaulin command"
    required: false

runs:
  using: "composite"
  steps:
#    - uses: Swatinem/rust-cache@v2
#      with:
#        workspaces: ". -> tarpaulin_target"

    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: "0.20.1"
        args: |
          --workspace
          --skip-clean
          --target-dir tarpaulin_target
          ${{ inputs.test_flags }}
