table:
  name: pending_applications
  schema: public
select_permissions:
  - role: public
    permission:
      columns:
        - contribution_id
        - contributor_account_address
        - applied_at
      filter: {}
