[package]
description = "testing utils (fixtures, mocks)"
edition = "2021"
license-file = "LICENSE"
name = "testing"
version = "0.1.0"

[lib]

[dependencies]
# Database
diesel = {version = "2.1.0", default-features = false, features = ["postgres","extras"]}

# Utils
uuid = {version = "1.3.3", default_features = false, features = [
  "v4",
]}

# Local dependencies
domain = {path = "../domain"}
infrastructure = {path = "../infrastructure"}
