default:
  amqp:
    connection_retry_interval_ms: 6000
    connection_retry_count: 100

local:
  database:
    url: postgres://postgres:postgres@db/marketplace_db
    pool_max_size: 20
  amqp:
    url: amqp://rabbitmq:5672/%2f
  tracer:
    json: false
    ansi: true
    location: true

production:
  database:
    url: $DATABASE_URL
    pool_max_size: 3
  amqp:
    url: $CLOUDAMQP_URL
  tracer:
    json: true
    ansi: false
    location: true
