table:
  name: users
  schema: auth
configuration:
  column_config:
    active_mfa_type:
      custom_name: activeMfaType
    avatar_url:
      custom_name: avatarUrl
    created_at:
      custom_name: createdAt
    default_role:
      custom_name: defaultRole
    disabled:
      custom_name: disabled
    display_name:
      custom_name: displayName
    email:
      custom_name: email
    email_verified:
      custom_name: emailVerified
    id:
      custom_name: id
    is_anonymous:
      custom_name: isAnonymous
    last_seen:
      custom_name: lastSeen
    locale:
      custom_name: locale
    new_email:
      custom_name: newEmail
    otp_hash:
      custom_name: otpHash
    otp_hash_expires_at:
      custom_name: otpHashExpiresAt
    otp_method_last_used:
      custom_name: otpMethodLastUsed
    password_hash:
      custom_name: passwordHash
    phone_number:
      custom_name: phoneNumber
    phone_number_verified:
      custom_name: phoneNumberVerified
    ticket:
      custom_name: ticket
    ticket_expires_at:
      custom_name: ticketExpiresAt
    totp_secret:
      custom_name: totpSecret
    updated_at:
      custom_name: updatedAt
    webauthn_current_challenge:
      custom_name: currentChallenge
  custom_column_names:
    active_mfa_type: activeMfaType
    avatar_url: avatarUrl
    created_at: createdAt
    default_role: defaultRole
    disabled: disabled
    display_name: displayName
    email: email
    email_verified: emailVerified
    id: id
    is_anonymous: isAnonymous
    last_seen: lastSeen
    locale: locale
    new_email: newEmail
    otp_hash: otpHash
    otp_hash_expires_at: otpHashExpiresAt
    otp_method_last_used: otpMethodLastUsed
    password_hash: passwordHash
    phone_number: phoneNumber
    phone_number_verified: phoneNumberVerified
    ticket: ticket
    ticket_expires_at: ticketExpiresAt
    totp_secret: totpSecret
    updated_at: updatedAt
    webauthn_current_challenge: currentChallenge
  custom_name: users
  custom_root_fields:
    delete: deleteUsers
    delete_by_pk: deleteUser
    insert: insertUsers
    insert_one: insertUser
    select: users
    select_aggregate: usersAggregate
    select_by_pk: user
    update: updateUsers
    update_by_pk: updateUser
object_relationships:
  - name: defaultRoleByRole
    using:
      foreign_key_constraint_on: default_role
  - name: githubUser
    using:
      manual_configuration:
        column_mapping:
          id: user_id
        insertion_order: null
        remote_table:
          name: github_users
          schema: auth
  - name: userInfo
    using:
      manual_configuration:
        column_mapping:
          id: user_id
        insertion_order: null
        remote_table:
          name: user_info
          schema: public
array_relationships:
  - name: projectsLeaded
    using:
      manual_configuration:
        column_mapping:
          id: user_id
        insertion_order: null
        remote_table:
          name: project_leads
          schema: public
  - name: refreshTokens
    using:
      foreign_key_constraint_on:
        column: user_id
        table:
          name: refresh_tokens
          schema: auth
  - name: roles
    using:
      foreign_key_constraint_on:
        column: user_id
        table:
          name: user_roles
          schema: auth
  - name: securityKeys
    using:
      foreign_key_constraint_on:
        column: user_id
        table:
          name: user_security_keys
          schema: auth
  - name: userProviders
    using:
      foreign_key_constraint_on:
        column: user_id
        table:
          name: user_providers
          schema: auth
select_permissions:
  - role: public
    permission:
      columns:
        - avatar_url
        - display_name
        - id
      filter: {}
  - role: registered_user_specific
    permission:
      columns:
        - active_mfa_type
        - avatar_url
        - created_at
        - default_role
        - disabled
        - display_name
        - email
        - email_verified
        - id
        - is_anonymous
        - locale
        - metadata
        - new_email
        - phone_number
        - phone_number_verified
      filter:
        id:
          _eq: X-Hasura-User-Id
update_permissions:
  - role: registered_user_specific
    permission:
      columns:
        - email
        - metadata
      filter:
        id:
          _eq: X-Hasura-User-Id
      check: null
event_triggers:
  - name: auth_users_update
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: HASURA_EVENT_WEBHOOK
    headers:
      - name: environment
        value_from_env: ENV
    request_transform:
      body:
        action: transform
        template: |-
          {
            "event": {
              "op": {{$body?.event?.op}},
              "data": {
                "old": {
                  "last_seen": {{$body?.event?.data?.old?.last_seen}},
                  "metadata": {{$body?.event?.data?.old?.metadata}},
                  "id": {{$body?.event?.data?.old?.id}},
                  "created_at": {{$body?.event?.data?.old?.created_at}},
                  "updated_at": {{$body?.event?.data?.old?.updated_at}},
                  "disabled": {{$body?.event?.data?.old?.disabled}},
                  "email_verified": {{$body?.event?.data?.old?.email_verified}},
                  "phone_number_verified": {{$body?.event?.data?.old?.phone_number_verified}},
                  "otp_hash_expires_at": {{$body?.event?.data?.old?.otp_hash_expires_at}},
                  "is_anonymous": {{$body?.event?.data?.old?.is_anonymous}},
                  "ticket_expires_at": {{$body?.event?.data?.old?.ticket_expires_at}},
                  "locale": {{$body?.event?.data?.old?.locale}},
                  "email": {{$body?.event?.data?.old?.email}},
                  "phone_number": {{$body?.event?.data?.old?.phone_number}},
                  "password_hash": {{$body?.event?.data?.old?.password_hash}},
                  "new_email": {{$body?.event?.data?.old?.new_email}},
                  "otp_method_last_used": {{$body?.event?.data?.old?.otp_method_last_used}},
                  "otp_hash": {{$body?.event?.data?.old?.otp_hash}},
                  "totp_secret": {{$body?.event?.data?.old?.totp_secret}},
                  "active_mfa_type": {{$body?.event?.data?.old?.active_mfa_type}},
                  "ticket": {{$body?.event?.data?.old?.ticket}},
                  "webauthn_current_challenge": {{$body?.event?.data?.old?.webauthn_current_challenge}},
                  "display_name": {{$body?.event?.data?.old?.display_name}},
                  "avatar_url": {{$body?.event?.data?.old?.avatar_url}},
                  "default_role": {{$body?.event?.data?.old?.default_role}}
                },
                "new": {
                  "last_seen": {{$body?.event?.data?.new?.last_seen}},
                  "metadata": {{$body?.event?.data?.new?.metadata}},
                  "id": {{$body?.event?.data?.new?.id}},
                  "created_at": {{$body?.event?.data?.new?.created_at}},
                  "updated_at": {{$body?.event?.data?.new?.updated_at}},
                  "disabled": {{$body?.event?.data?.new?.disabled}},
                  "email_verified": {{$body?.event?.data?.new?.email_verified}},
                  "phone_number_verified": {{$body?.event?.data?.new?.phone_number_verified}},
                  "otp_hash_expires_at": {{$body?.event?.data?.new?.otp_hash_expires_at}},
                  "is_anonymous": {{$body?.event?.data?.new?.is_anonymous}},
                  "ticket_expires_at": {{$body?.event?.data?.new?.ticket_expires_at}},
                  "locale": {{$body?.event?.data?.new?.locale}},
                  "email": {{$body?.event?.data?.new?.email}},
                  "phone_number": {{$body?.event?.data?.new?.phone_number}},
                  "password_hash": {{$body?.event?.data?.new?.password_hash}},
                  "new_email": {{$body?.event?.data?.new?.new_email}},
                  "otp_method_last_used": {{$body?.event?.data?.new?.otp_method_last_used}},
                  "otp_hash": {{$body?.event?.data?.new?.otp_hash}},
                  "totp_secret": {{$body?.event?.data?.new?.totp_secret}},
                  "active_mfa_type": {{$body?.event?.data?.new?.active_mfa_type}},
                  "ticket": {{$body?.event?.data?.new?.ticket}},
                  "webauthn_current_challenge": {{$body?.event?.data?.new?.webauthn_current_challenge}},
                  "display_name": {{$body?.event?.data?.new?.display_name}},
                  "avatar_url": {{$body?.event?.data?.new?.avatar_url}},
                  "default_role": {{$body?.event?.data?.new?.default_role}}
                }
              },
              "trace_context": {
                "trace_id": {{$body?.event?.trace_context?.trace_id}},
                "span_id": {{$body?.event?.trace_context?.span_id}}
              }
            },
            "created_at": {{$body?.created_at}},
            "id": {{$body?.id}},
            "delivery_info": {
              "max_retries": {{$body?.delivery_info?.max_retries}},
              "current_retry": {{$body?.delivery_info?.current_retry}}
            },
            "trigger": {
              "name": {{$body?.trigger?.name}}
            },
            "table": {
              "schema": {{$body?.table?.schema}},
              "name": {{$body?.table?.name}}
            }
          }
      template_engine: Kriti
      version: 2
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
