table:
  name: budgets
  schema: public
object_relationships:
  - name: project
    using:
      manual_configuration:
        column_mapping:
          project_id: id
        insertion_order: null
        remote_table:
          name: projects
          schema: public
array_relationships:
  - name: paymentRequests
    using:
      manual_configuration:
        column_mapping:
          id: budget_id
        insertion_order: null
        remote_table:
          name: payment_requests
          schema: public
select_permissions:
  - role: public
    permission:
      columns:
        - id
        - initial_amount
        - project_id
        - remaining_amount
        - spent_amount
      filter: {}
      allow_aggregations: true
event_triggers:
  - name: budget_update
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: HASURA_EVENT_WEBHOOK
    headers:
      - name: environment
        value_from_env: ENV
    request_transform:
      body:
        action: transform
        template: |-
          {
            "event": {
              "op": {{$body?.event?.op}},
              "data": {
                "old": {
                  "project_id": {{$body?.event?.data?.old?.project_id}},
                  "initial_amount": {{$body?.event?.data?.old?.initial_amount}},
                  "remaining_amount": {{$body?.event?.data?.old?.remaining_amount}},
                  "id": {{$body?.event?.data?.old?.id}},
                  "spent_amount": {{$body?.event?.data?.old?.spent_amount}}
                },
                "new": {
                  "project_id": {{$body?.event?.data?.new?.project_id}},
                  "initial_amount": {{$body?.event?.data?.new?.initial_amount}},
                  "remaining_amount": {{$body?.event?.data?.new?.remaining_amount}},
                  "id": {{$body?.event?.data?.new?.id}},
                  "spent_amount": {{$body?.event?.data?.new?.spent_amount}}
                }
              },
              "trace_context": {
                "trace_id": {{$body?.event?.trace_context?.trace_id}},
                "span_id": {{$body?.event?.trace_context?.span_id}}
              }
            },
            "created_at": {{$body?.created_at}},
            "id": {{$body?.id}},
            "delivery_info": {
              "max_retries": {{$body?.delivery_info?.max_retries}},
              "current_retry": {{$body?.delivery_info?.current_retry}}
            },
            "trigger": {
              "name": {{$body?.trigger?.name}}
            },
            "table": {
              "schema": {{$body?.table?.schema}},
              "name": {{$body?.table?.name}}
            }
          }
      template_engine: Kriti
      version: 2
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
