table:
  name: payment_requests
  schema: public
object_relationships:
  - name: budget
    using:
      manual_configuration:
        column_mapping:
          budget_id: id
        insertion_order: null
        remote_table:
          name: budgets
          schema: public
  - name: githubRecipient
    using:
      manual_configuration:
        column_mapping:
          recipient_id: id
        insertion_order: null
        remote_table:
          name: github_users
          schema: public
  - name: recipient
    using:
      manual_configuration:
        column_mapping:
          recipient_id: github_user_id
        insertion_order: null
        remote_table:
          name: github_users
          schema: auth
  - name: requestor
    using:
      manual_configuration:
        column_mapping:
          requestor_id: id
        insertion_order: null
        remote_table:
          name: users
          schema: auth
array_relationships:
  - name: payments
    using:
      manual_configuration:
        column_mapping:
          id: request_id
        insertion_order: null
        remote_table:
          name: payments
          schema: public
  - name: workItems
    using:
      manual_configuration:
        column_mapping:
          id: payment_id
        insertion_order: null
        remote_table:
          name: work_items
          schema: public
remote_relationships:
  - definition:
      to_remote_schema:
        lhs_fields:
          - recipient_id
        remote_field:
          fetchUserDetailsById:
            arguments:
              userId: $recipient_id
        remote_schema: GithubProxy
    name: liveGithubRecipient
select_permissions:
  - role: public
    permission:
      columns:
        - amount_in_usd
        - budget_id
        - id
        - invoice_received_at
        - recipient_id
        - requested_at
        - requestor_id
      filter: {}
      allow_aggregations: true
event_triggers:
  - name: payment_request_update
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: HASURA_EVENT_WEBHOOK
    headers:
      - name: environment
        value_from_env: ENV
    request_transform:
      body:
        action: transform
        template: |-
          {
            "event": {
              "op": {{$body?.event?.op}},
              "data": {
                "old": {
                  "invoice_received_at": {{$body?.event?.data?.old?.invoice_received_at}},
                  "id": {{$body?.event?.data?.old?.id}},
                  "hours_worked": {{$body?.event?.data?.old?.hours_worked}},
                  "budget_id": {{$body?.event?.data?.old?.budget_id}},
                  "requestor_id": {{$body?.event?.data?.old?.requestor_id}},
                  "recipient_id": {{$body?.event?.data?.old?.recipient_id}},
                  "amount_in_usd": {{$body?.event?.data?.old?.amount_in_usd}},
                  "requested_at": {{$body?.event?.data?.old?.requested_at}}
                },
                "new": {
                  "invoice_received_at": {{$body?.event?.data?.new?.invoice_received_at}},
                  "id": {{$body?.event?.data?.new?.id}},
                  "hours_worked": {{$body?.event?.data?.new?.hours_worked}},
                  "budget_id": {{$body?.event?.data?.new?.budget_id}},
                  "requestor_id": {{$body?.event?.data?.new?.requestor_id}},
                  "recipient_id": {{$body?.event?.data?.new?.recipient_id}},
                  "amount_in_usd": {{$body?.event?.data?.new?.amount_in_usd}},
                  "requested_at": {{$body?.event?.data?.new?.requested_at}}
                }
              },
              "trace_context": {
                "trace_id": {{$body?.event?.trace_context?.trace_id}},
                "span_id": {{$body?.event?.trace_context?.span_id}}
              }
            },
            "created_at": {{$body?.created_at}},
            "id": {{$body?.id}},
            "delivery_info": {
              "max_retries": {{$body?.delivery_info?.max_retries}},
              "current_retry": {{$body?.delivery_info?.current_retry}}
            },
            "trigger": {
              "name": {{$body?.trigger?.name}}
            },
            "table": {
              "schema": {{$body?.table?.schema}},
              "name": {{$body?.table?.name}}
            }
          }
      template_engine: Kriti
      version: 2
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
