table:
  name: user_info
  schema: public
insert_permissions:
  - role: registered_user_specific
    permission:
      check:
        user_id:
          _eq: X-Hasura-User-Id
      columns:
        - identity
        - location
        - payout_settings
        - contact_information
        - user_id
select_permissions:
  - role: public
    permission:
      columns:
        - are_payout_settings_valid
        - user_id
      filter: {}
  - role: registered_user_specific
    permission:
      columns:
        - identity
        - location
        - payout_settings
        - contact_information
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
update_permissions:
  - role: registered_user_specific
    permission:
      columns:
        - identity
        - location
        - payout_settings
        - contact_information
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      check:
        user_id:
          _eq: X-Hasura-User-Id
delete_permissions:
  - role: registered_user_specific
    permission:
      filter:
        user_id:
          _eq: X-Hasura-User-Id
event_triggers:
  - name: user_profile_update
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: HASURA_EVENT_WEBHOOK
    headers:
      - name: environment
        value_from_env: ENV
    request_transform:
      body:
        action: transform
        template: |-
          {
            "event": {
              "op": {{$body?.event?.op}},
              "data": {
                "old": {
                  "user_id": {{$body?.event?.data?.old?.user_id}},
                  "identity": {{$body?.event?.data?.old?.identity}},
                  "location": {{$body?.event?.data?.old?.location}},
                  "contact_information": {{$body?.event?.data?.old?.contact_information}},
                  "are_payout_settings_valid": {{$body?.event?.data?.old?.are_payout_settings_valid}},
                  "payout_settings": {{$body?.event?.data?.old?.payout_settings}}
                },
                "new": {
                  "user_id": {{$body?.event?.data?.new?.user_id}},
                  "identity": {{$body?.event?.data?.new?.identity}},
                  "location": {{$body?.event?.data?.new?.location}},
                  "contact_information": {{$body?.event?.data?.new?.contact_information}},
                  "are_payout_settings_valid": {{$body?.event?.data?.new?.are_payout_settings_valid}},
                  "payout_settings": {{$body?.event?.data?.new?.payout_settings}}
                }
              },
              "trace_context": {
                "trace_id": {{$body?.event?.trace_context?.trace_id}},
                "span_id": {{$body?.event?.trace_context?.span_id}}
              }
            },
            "created_at": {{$body?.created_at}},
            "id": {{$body?.id}},
            "delivery_info": {
              "max_retries": {{$body?.delivery_info?.max_retries}},
              "current_retry": {{$body?.delivery_info?.current_retry}}
            },
            "trigger": {
              "name": {{$body?.trigger?.name}}
            },
            "table": {
              "schema": {{$body?.table?.schema}},
              "name": {{$body?.table?.name}}
            }
          }
      template_engine: Kriti
      version: 2
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
