table:
  name: projects
  schema: public
object_relationships:
  - name: projectDetails
    using:
      manual_configuration:
        column_mapping:
          id: project_id
        insertion_order: null
        remote_table:
          name: project_details
          schema: public
array_relationships:
  - name: budgets
    using:
      manual_configuration:
        column_mapping:
          id: project_id
        insertion_order: null
        remote_table:
          name: budgets
          schema: public
  - name: contributors
    using:
      manual_configuration:
        column_mapping:
          id: project_id
        insertion_order: null
        remote_table:
          name: projects_contributors_view
          schema: public
  - name: githubRepos
    using:
      manual_configuration:
        column_mapping:
          id: project_id
        insertion_order: null
        remote_table:
          name: project_github_repos
          schema: public
  - name: pendingInvitations
    using:
      manual_configuration:
        column_mapping:
          id: project_id
        insertion_order: null
        remote_table:
          name: pending_project_leader_invitations
          schema: public
  - name: projectLeads
    using:
      manual_configuration:
        column_mapping:
          id: project_id
        insertion_order: null
        remote_table:
          name: project_leads
          schema: public
  - name: projectSponsors
    using:
      foreign_key_constraint_on:
        column: project_id
        table:
          name: projects_sponsors
          schema: public
select_permissions:
  - role: public
    permission:
      columns:
        - id
      filter: {}
event_triggers:
  - name: projects_update
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: HASURA_EVENT_WEBHOOK
    headers:
      - name: environment
        value_from_env: ENV
    request_transform:
      body:
        action: transform
        template: |-
          {
            "event": {
              "op": {{$body?.event?.op}},
              "data": {
                "old": {
                  "id": {{$body?.event?.data?.old?.id}}
                },
                "new": {
                  "id": {{$body?.event?.data?.new?.id}}
                }
              },
              "trace_context": {
                "trace_id": {{$body?.event?.trace_context?.trace_id}},
                "span_id": {{$body?.event?.trace_context?.span_id}}
              }
            },
            "created_at": {{$body?.created_at}},
            "id": {{$body?.id}},
            "delivery_info": {
              "max_retries": {{$body?.delivery_info?.max_retries}},
              "current_retry": {{$body?.delivery_info?.current_retry}}
            },
            "trigger": {
              "name": {{$body?.trigger?.name}}
            },
            "table": {
              "schema": {{$body?.table?.schema}},
              "name": {{$body?.table?.name}}
            }
          }
      template_engine: Kriti
      version: 2
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
