table:
  name: pending_project_leader_invitations
  schema: public
object_relationships:
  - name: githubUser
    using:
      manual_configuration:
        column_mapping:
          github_user_id: github_user_id
        insertion_order: null
        remote_table:
          name: github_users
          schema: auth
  - name: project
    using:
      manual_configuration:
        column_mapping:
          project_id: id
        insertion_order: null
        remote_table:
          name: projects
          schema: public
select_permissions:
  - role: public
    permission:
      columns:
        - github_user_id
        - id
        - project_id
      filter: {}
  - role: registered_user_specific
    permission:
      columns:
        - github_user_id
        - id
        - project_id
      filter: {}
event_triggers:
  - name: project_lead_invitation_update
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook_from_env: HASURA_EVENT_WEBHOOK
    headers:
      - name: environment
        value_from_env: ENV
    request_transform:
      body:
        action: transform
        template: |-
          {
            "event": {
              "op": {{$body?.event?.op}},
              "data": {
                "old": {
                  "project_id": {{$body?.event?.data?.old?.project_id}},
                  "github_user_id": {{$body?.event?.data?.old?.github_user_id}},
                  "id": {{$body?.event?.data?.old?.id}}
                },
                "new": {
                  "project_id": {{$body?.event?.data?.new?.project_id}},
                  "github_user_id": {{$body?.event?.data?.new?.github_user_id}},
                  "id": {{$body?.event?.data?.new?.id}}
                }
              },
              "trace_context": {
                "trace_id": {{$body?.event?.trace_context?.trace_id}},
                "span_id": {{$body?.event?.trace_context?.span_id}}
              }
            },
            "created_at": {{$body?.created_at}},
            "id": {{$body?.id}},
            "delivery_info": {
              "max_retries": {{$body?.delivery_info?.max_retries}},
              "current_retry": {{$body?.delivery_info?.current_retry}}
            },
            "trigger": {
              "name": {{$body?.trigger?.name}}
            },
            "table": {
              "schema": {{$body?.table?.schema}},
              "name": {{$body?.table?.name}}
            }
          }
      template_engine: Kriti
      version: 2
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
