table:
  name: payout_settings
  schema: public
insert_permissions:
  - role: registered_user_specific
    permission:
      check:
        user_id:
          _eq: X-Hasura-User-Id
      columns:
        - eth_wallet_address
        - user_id
select_permissions:
  - role: registered_user_specific
    permission:
      columns:
        - eth_wallet_address
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
update_permissions:
  - role: registered_user_specific
    permission:
      columns:
        - eth_wallet_address
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      check: null
delete_permissions:
  - role: registered_user_specific
    permission:
      filter:
        user_id:
          _eq: X-Hasura-User-Id
