[package]
name = "marketplace-wrappers"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
uuid = { version = "1.1.2" }
crypto-bigint = { version = "0.4.8" }
