[package]
edition = "2021"
license-file = "LICENSE"
name = "marketplace-wrappers"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
crypto-bigint = {version = "0.4.8"}
quote = "1.0"
syn = "1.0"
uuid = {version = "1.1.2"}
