name: Setup environment

description: Run docker-compose and run database migrations

runs:
  using: "composite"
  steps:
    - name: Run docker-compose
      shell: bash
      run: docker-compose up -d
      env:
        BACKEND_GRAPHQL_URL: https://staging.api.onlydust.xyz/graphql

    - name: Install diesel CLI
      shell: bash
      run: cargo install diesel_cli --no-default-features --features postgres --force

    - name: Run migrations
      shell: bash
      run: diesel migration run
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost/marketplace_db
