name: Setup environment

description: Run docker-compose and run database migrations

runs:
  using: "composite"
  steps:
    - name: Run docker-compose
      shell: bash
      run: docker compose up -d
