[package]
description = "testing utils (fixtures, mocks)"
edition = "2021"
license-file = "LICENSE"
name = "testing"
version = "0.1.0"

[lib]

[dependencies]
# Database
diesel = {version = "1.4.8", default-features = false, features = [
  "postgres",
]}
r2d2 = "0.8.10"
r2d2-diesel = "1.0.0"

# Utils
uuid = {version = "0.8.2", default_features = false, features = [
  "v4",
]}

# Local dependencies
domain = {path = "../domain"}
infrastructure = {path = "../infrastructure"}
