name: Setup cargo

description: Install Rust toolchain and use cargo cache to speed up compilation time

inputs:
  components:
    description: Rust components to install
    required: false
    default: ''

  key:
    description: Specific key for the cargo cache
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.63
        components: ${{ inputs.components }}
        override: true

    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ inputs.key }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ inputs.key }}-
          ${{ runner.os }}-cargo-
