name: Kill Rust backend

description: Kill running Rust backends

runs:
  using: "composite"
  steps:
    - name: Kill all running backends
      shell: bash
      run: kill ${{ env.api_pid }} ${{ env.event_store_pid }} ${{ env.event_listeners_pid }} ${{ env.github_indexer_pid }} ${{ env.github_proxy_pid }}

