name: Compile application

description: Run cargo build command using 'action-rs/cargo'

runs:
  using: "composite"
  steps:
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
