default:
  database:
    pool_max_size: 3
    url: $DATABASE_URL
  github:
    base_url: $GITHUB_BASE_URL
    personal_access_tokens: $GITHUB_PAT
    max_calls_per_request: $GITHUB_MAX_CALLS_PER_REQUEST
  http:
    api_keys:
      - $GITHUB_INDEXER_API_KEY

local:
  tracer:
    json: false
    ansi: true
    location: true

production:
  tracer:
    json: true
    ansi: false
    location: true
