name: Playwright Tests

description: Install and run Playwright tests

runs:
  using: "composite"
  steps:
    - name: Install Playwright Browsers
      shell: bash
      run: yarn playwright install --with-deps chromium

    - name: Run Playwright tests
      shell: bash
      run: yarn playwright test
