name: Playwright Tests

description: Install and run Playwright tests

runs:
  using: "composite"
  steps:
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Set up node modules cache
      uses: actions/cache@v3
      continue-on-error: true
      with:
        path: |
          node_modules/
        key: ${{ runner.os }}-playwright-node-modules-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-playwright-node-modules-

    - name: Install Playwright Browsers
      shell: bash
      run: yarn playwright install --with-deps chromium

    - name: Run Playwright tests
      shell: bash
      run: yarn playwright test

    - uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
