local:
  database:
    url: postgres://postgres:postgres@localhost/marketplace_db
    pool_max_size: 20
  amqp:
    url: "amqp://127.0.0.1:5672/%2f"
  graphql:
    url: "http://localhost:8080/v1/graphql"
    admin_secret: $HASURA_GRAPHQL_ADMIN_SECRET
  tracer:
    ansi: true

production:
  database:
    url: $DATABASE_URL
    pool_max_size: 3
  amqp:
    url: $CLOUDAMQP_URL
  graphql:
    url: $HASURA_GRAPHQL_GRAPHQL_URL
    admin_secret: $HASURA_GRAPHQL_ADMIN_SECRET
  tracer:
    ansi: false
