name: CI

on:
  pull_request: ~

  push:
    branches:
      - "main"

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DATABASE_URL: postgres://postgres:postgres@localhost/marketplace_db
  RUST_LOG: info
  HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"5152fa850c02dc222631cca898ed1485821a70912a6e3649c49076912daa3b62182ba013315915d64f40cddfbb8b58eb5bd11ba225336a6af45bbae07ca873f3","issuer":"hasura-auth"}'

jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          override: true

      - name: Check code formatting
        run: cargo +nightly fmt -- --check

      - name: Check codecov.yml file format
        run: curl --data-binary @- https://codecov.io/validate < codecov.yml

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup cargo
        uses: ./.github/actions/cargo-setup

      - name: Check application
        uses: actions-rs/cargo@v1
        with:
          command: check

  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup cargo
        uses: ./.github/actions/cargo-setup

      - name: Compile application
        uses: actions-rs/cargo@v1
        with:
          command: build

  lint:
    name: Clippy checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup cargo
        uses: ./.github/actions/cargo-setup

      - name: Setup clippy
        run: rustup component add clippy

      - name: Annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --bins --tests --examples -- -D warnings

  hasura_inconsistencies:
    name: Database and GraphQL Schema consistency
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup cargo
        uses: ./.github/actions/cargo-setup

      - name: Setup environment
        uses: ./.github/actions/env-setup

      - name: Run Rust backend
        uses: ./.github/actions/backend-run

      - name: Install Hasura CLI
        uses: ./.github/actions/hasura-setup

      - name: Check inconsistencies
        run: yarn hasura md ic status
        working-directory: ./hasura

      - name: Log inconsistencies list on failure
        if: ${{ failure() }}
        run: yarn hasura md ic list
        working-directory: ./hasura

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup cargo
        uses: ./.github/actions/cargo-setup

      - name: Setup environment
        uses: ./.github/actions/env-setup

      - name: Run migrations
        uses: ./.github/actions/migrations-run

      - name: Run tests
        uses: ./.github/actions/coverage-checks

      - name: Upload coverage results
        uses: ./.github/actions/coverage-upload
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          codecov_flag: unittest

  e2e_tests:
    name: End-to-end tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup cargo
        uses: ./.github/actions/cargo-setup

      - name: Setup llvm tools
        run: rustup component add llvm-tools-preview

      - name: Setup environment
        uses: ./.github/actions/env-setup

      - name: Run Rust backend
        uses: ./.github/actions/backend-run
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: -Cinstrument-coverage
          LLVM_PROFILE_FILE: backend-%p-%m.profraw

      - name: Setup hasura
        uses: ./.github/actions/hasura-setup

      - name: Execute end-to-end tests
        uses: ./.github/actions/cypress

      - name: Kill Rust backend
        uses: ./.github/actions/backend-kill

      - name: Install grcov
        uses: actions-rs/install@v0.1
        with:
          crate: grcov

      - name: Build coverage file
        run: |
          grcov . \
            --binary-path ./target/debug/deps/ \
            -s . \
            -t cobertura \
            --branch \
            --ignore-not-existing \
            --ignore '../*' \
            --ignore "/*" \
            -o cobertura.xml

      - name: Upload coverage results
        uses: ./.github/actions/coverage-upload
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          codecov_flag: e2e

      - name: Setup tmate session for debugging
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() && inputs.debug_enabled }}
