name: Coverage

on:
  push:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Code coverage analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Code coverage
        uses: ./.github/actions/coverage-checks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
