name: Coverage

on:
  pull_request: ~
  push:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Code coverage analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/cargo-setup
      - uses: ./.github/actions/env-setup
      - uses: ./.github/actions/compile-application

      - uses: ./.github/actions/run-application
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.20.1'
          timeout: 180 # TODO: Remove once starknet client dependency is gone
          args: '--all-features -- --test-threads 1'
        env:
          API_KEY: ROOT
          E2E_WAITING_TIME: 60

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: cobertura.xml

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
