name: Coverage

on:
  push:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_COLOR: always
  API_KEY: ROOT
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DATABASE_URL: postgres://postgres:postgres@localhost/marketplace_db
  GITHUB_ID: githubid
  GITHUB_SECRET: githubsecret
  CONTRIBUTIONS_ADDRESS: "0x03f0e236a4cb1b20278ad5a7e790b29c6e5bac25c34fc3fb0c092f8e5275b512"
  NETWORK: devnet
  APIBARA_NODE_URL: http://localhost:7171
  API_URL: http://localhost:8000
  RUST_LOG: info
  IS_VALID_SIGNATURE_SELECTOR: isValidSignature
  GITHUB_ACCESS_TOKEN_URL: http://localhost:5001/token
  GITHUB_USER_API_URL: http://localhost:5001/user

jobs:
  unittest:
    name: Code coverage analysis [unittests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup cargo
        uses: ./.github/actions/cargo-setup
        with:
          key: coverage

      - name: Code coverage
        uses: ./.github/actions/coverage-checks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          codecov_flag: unittests

  infrastructure-tests:
    name: Code coverage analysis [infrastructure]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup cargo
        uses: ./.github/actions/cargo-setup
        with:
          key: coverage

      - name: Setup environment
        uses: ./.github/actions/env-setup

      - name: Code coverage
        uses: ./.github/actions/coverage-checks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          test_flags: -p marketplace-infrastructure --features with_infrastructure_tests -- --ignored
          codecov_flag: infrastructure

  component-tests:
    name: Code coverage analysis [component]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup cargo
        uses: ./.github/actions/cargo-setup
        with:
          key: coverage

      - name: Setup environment
        uses: ./.github/actions/env-setup

      - name: Code coverage
        uses: ./.github/actions/coverage-checks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          test_flags: -p marketplace-core --features with_component_tests -- --ignored
          codecov_flag: component

  end-to-end:
    name: Code coverage analysis [end-to-end]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup cargo
        uses: ./.github/actions/cargo-setup
        with:
          key: coverage

      - name: Setup environment
        uses: ./.github/actions/env-setup

      - name: Code coverage
        uses: ./.github/actions/coverage-checks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
          test_flags: -p marketplace-tests --features with_e2e_tests -- --ignored --test-threads 1
          codecov_flag: e2e
