name: Deployment build

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  docker-build:
    uses: onlydustxyz/cicd/.github/workflows/docker-workflow.yml@main
    with:
      image_name: deathnote-contribution-feeder-rest-api
      image_tag: ${{ github.ref_name }}
      bin_name: marketplace_backend
      dockerfile: diesel-rocket-rs
      datadog_label: '[{"source": "deathnote", "service": "deathnote-contribution-feeder-rest-api"}]'
    secrets: inherit
