name: End-to-end tests

on:
  pull_request: ~
  push:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run end-to-end tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run docker compose
        run: BASE_TAG=latest docker-compose -f ./scripts/docker/dev/docker-compose.yml up -d

      - name: Build
        run: cargo build

      - name: Create environment file
        run: cp .env.example .env

      - name: Start the backend
        run: cargo run &
        env:
          RUST_LOG: debug
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait a bit for the back-end to warm up
        run: sleep 5

      - name: Run end-to-end tests
        run: cargo run --bin e2e
        env:
          RUST_LOG: debug
