name: End-to-end tests

on:
  pull_request: ~
  push:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run end-to-end tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Run docker compose
        run: BASE_TAG=latest docker-compose -f ./scripts/docker/dev/docker-compose.yml up -d

      - name: Build
        run: cargo build

      - name: Create environment file
        run: cp .env.example .env

      - name: Start the backend
        run: cargo run &
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for the backend to be ready
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http://localhost:8000/openapi.json

      - name: Run end-to-end tests
        run: cargo run --bin e2e
