name: End-to-end tests

on:
  pull_request: ~

env:
  CARGO_TERM_COLOR: always

jobs:
  e2e_tests:
    name: Execute end-to-end tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup cargo
        uses: ./.github/actions/cargo-setup

      - name: Setup environment
        uses: ./.github/actions/env-setup

      - name: Compile application
        uses: ./.github/actions/compile-application

      - name: Launch the backend
        uses: ./.github/actions/run-backend
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Launch the indexer
        uses: ./.github/actions/run-indexer
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          indexer_name: starknet

      - name: Execute end-to-end tests
        run: cargo test -p marketplace-tests --features with_e2e_tests e2e_tests
        env:
          API_KEY: ROOT
          E2E_WAITING_TIME: 60

      - name: Setup tmate session for debugging
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() && inputs.debug_enabled }}
