name: End-to-end tests

on:
  pull_request: ~

env:
  CARGO_TERM_COLOR: always

jobs:
  e2e_tests:
    name: End-to-end tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/run-application
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute e2e tests
        run: cargo test -p marketplace-tests --features with_e2e_tests e2e_tests
        env:
          API_KEY: ROOT
          E2E_WAITING_TIME: 60

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() && inputs.debug_enabled }}
