name: Frontend CI

on:
  pull_request: ~

  push:
    branches:
      - "main"
      - "hotfix/**"

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

env:
  VITE_ENV: local
  VITE_LANGUAGES_FILTER: CSS,Dockerfile,Handlebars,HTML,Jupyter Notebook,Makefile,Nix,SCSS,Shell
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install yarn
        run: npm install -g yarn
      - run: yarn frontend:install --frozen-lockfile
      - name: Build project
        run: yarn frontend:build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn frontend:install --frozen-lockfile
      - run: yarn frontend:lint

  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn frontend:install --frozen-lockfile
      - run: yarn frontend:dependency-cruiser

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn frontend:install --frozen-lockfile
      - name: Run unit/integration test
        run: yarn frontend:test --coverage
      - name: Setup tmate session for debugging
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() && inputs.debug_enabled }}
      - name: Upload unit/integration tests coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage/clover.xml
          token: ${{ secrets.CODECOV_TOKEN  }}
      - name: Clean coverage
        run: rm -rf coverage
