name: Frontend CI

on:
  pull_request: ~

  push:
    branches:
      - "main"
      - "develop"
      - "hotfix/**"

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

env:
  VITE_ENV: local

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install yarn
        run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - name: Build project
        run: yarn build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn dependency-cruiser

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - name: Run unit/integration test
        run: yarn test --coverage
      - name: Upload unit/integration tests coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage/clover.xml
          token: ${{ secrets.CODECOV_TOKEN  }}
      - name: Clean coverage
        run: rm -rf coverage
