name: Install

on:
  schedule:
    - cron: "0 2 * * *"

env:
  GITHUB_PAT: ${{ secrets.CI_GITHUB_TOKEN }}
  GITHUB_PAT_FOR_E2E_TESTS_USERS: ${{ secrets.CI_GITHUB_PAT_FOR_E2E_TESTS_USERS }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup cargo
        uses: ./.github/actions/cargo-setup

      - name: Install the stack
        run: make install
