name: test CI

on:
  workflow_call:

env:
  NEXT_PUBLIC_ENV: local
  NEXT_PUBLIC_LANGUAGES_FILTER: CSS,Dockerfile,Handlebars,HTML,Jupyter Notebook,Makefile,Nix,SCSS,Shell
  NODE_OPTIONS: --max_old_space_size=4096
  NEXT_PUBLIC_USE_APOLLO: "true"
  NEXT_PUBLIC_ONLYDUST_API_BASEPATH: "develop-api.onlydust.com"
  NEXT_PUBLIC_METADATA_ASSETS_S3_BUCKET: "https://od-metadata-assets-develop.s3.eu-west-1.amazonaws.com"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install -frozen-lockfile --prefer-offline
      - name: Run unit/integration test
        run: yarn test --coverage
      - name: Setup tmate session for debugging
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() && inputs.debug_enabled }}
      - name: Upload unit/integration tests coverage
        uses: codecov/codecov-action@v4
        with:
          files: coverage/clover.xml
          token: ${{ secrets.CODECOV_TOKEN  }}
      - name: Clean coverage
        run: rm -rf coverage
